require("user.options")
require("user.plugins")
require("user.keymaps")
require("user.colorscheme")
require("user.dressing")
require("user.cmp")
require("user.lsp")
require("user.nvim-navic")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.neo-tree")
-- require("user.nvim-tree")
require("user.bufferline")
require("user.toggleterm")
require("user.lualine2")
require("user.alpha")
require("user.whichkey")
require("user.fugitive")
require("user.harpoon")
require("user.filetype")
require("user.leap")
-- require("user.flash")
require("user.nvim-surround")
require("user.twilight")
require("user.neoclip")
require("user.nvim-notify")
require("user.trouble")
require("user.colorizer")
require("user.illuminate")
require("user.indent-blankline")
-- require("user.noice")
require("user.symbols-outline")
require("user.project")
require("user.ufo")
-- require("user.glow")
require("user.go")
require("user.navigator")
