[[language]]
name="fortran"
scope="source.fortran"
injection-regex = "fortran"
auto-format=true
file-types = ["f", "for", "f90", "f95", "f03", "F90", "inc", "part"]
roots = ["fpm.toml", ".fortls"]
comment-token = "!"
indent={tab-width=2, unit="  "}
language-server = {command="fortls", args=["--notify_init", "--sort_keywords", "--hover_signature", "--hover_language", "fortran", "--use_signature_help"]}
formatter={command="fprettify", args = [
        "--case",
        "2",
        "2",
        "2",
        "2",
        "--line-length",
        "78",
        "--indent",
        "2",
        "--strict-indent",
        "--disable-indent-mod",
        "--whitespace",
        "2",
        "--whitespace-comma",
        "--whitespace-assignment",
        "--enable-decl",
        "--whitespace-decl",
        "--whitespace-relational",
        "--whitespace-logical",
        "--whitespace-multdiv",
        "--whitespace-print",
        "--whitespace-intrinsics",
        "--strip-comments"]}


# [[grammar]]
# name = "fortran"
# source = { path = "/home/easifem/Dropbox/tree-sitter-fortran" }

[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name="python"
auto-format=true
formatter={command="black", args=["--quite"]}
