wsl = false
multigrid = true
vsync = true
maximized = false
srgb = false
idle = true
neovim_bin = "/opt/homebrew/bin/nvim"
frame = "transparent"

[font]
normal = ["FiraCode Nerd Font Mono"]
size = 14.0
